export const projectsData = [
	{
		title: "Mama's Choice",
		url: "https://mamaschoice.in/",
		image: "/projects/mamaschoice.jpg",
		description: "Mamas choice is a catalog website for an infant clothing brand. It is built using Next.js.",
		languages: ["TypeScript", "Next.js"],
		
	},
	{
		title: "Focus Technolab",
		url: "https://www.focustechnolab.com/",
		image: "/projects/focustechnolab.png",
		description: "Focus Technolab is a website for a software development company. It is built using Next.js.",
		languages: ["TypeScript", "Next.js"],
	},
	{
		title: "BDICC",
		url: "https://www.bluediamondicc.com/",
		image: "/projects/bdicc.png",
		description: "Blue Diamond ICC is a website for my convention center located in Kerala, India. It is built using Next.js.",
		languages: ["JavaScript", "Next.js"],
	},
	{
		title: "Tekloom",
		url: "https://tekloom.com/",
		image: "/projects/tekloom.png",
		description: "Tekloom is a website for a software development company. It is built using Next.js.",
		languages: ["JavaScript", "Next.js"],
	},
	{
		title: "Ignite AI",
		url: "https://discover.igniteme.in/",
		image: "/projects/ignite.png",
		description: "Ignite AI is an AI based chat bot that assesses the strengths and weaknesses of students and provides them with a personalized career path. It is built using React.js and MongoDb.",
		languages: ["JavaScript", "React", "MongoDb", "AI"],
	},
	{
		title: "Seed Innovations",
		url: "https://www.seedinnovations.in/",
		image: "/projects/seedinnvoations.png",
		description: "Seed Innovations is a website for a technology company. It is built using Next.js.",
		languages: ["JavaScript", "Next.js", "MongoDb"],
	},
	{
		title: "E-Janamaithri",
		url: "https://github.com/hamsathul/e-janamaithri",
		image: "/projects/ejanamaithri.png",
		description: "E-Janamaithri is a web application that helps the police department to manage the complaints and cases. It is built using Django.",
		languages: ["Python", "Django", "Sqlite"],
	},
	{
		title: "BD Tailoring",
		url: "https://www.bluediamond.ae/",
		image: "/projects/bluediamondae.png",
		description: "Blue Diamond Tailoring is a website for my abaya manufacturing company. It is built using Next.js.",
		languages: ["JavaScript", "Next.js"],
	},
	{
		title: "Moi App (Hackathon Project)",
		url: "https://moi-app.vercel.app/",
		image: "/projects/moi.png",
		description: "Moi App is our teams implementation of our hackathon project. it is built using Next.js, three.js.",
		languages: ["JavaScript", "Next.js", "Three.js"],
	},
	{
		title: "Nextjs Dashboard",
		url: "https://nextjs-dashboard-lime-alpha-54.vercel.app/dashboard",
		image: "/projects/nextdashboard.png",
		description: "A simple dashboard built using Next.js and postgres.",
		languages: ["Typescript", "Next.js", "Postgres"],
	},
	{
		title: "Cub3D",
		url: "https://github.com/samiyazbr/Cub3D",
		image: "/projects/42logo.jpg",
		description: "cub3d is a 3D maze game built using C and Raycasting algorithm. It is a project from 42 school curriculum.",
		languages: ["C", "42Project"],
	},
	{
		title: "ft_irc",
		url: "https://github.com/Aztaro97/ft_irc",
		image: "/projects/42logo.jpg",
		description: "ft_irc is a simple IRC server and client built using C++. It is a project from 42 school curriculum.",
		languages: ["C++", "42Project"],
	},

];