export const projectsData = [
	{
		title: "Mama's Choice",
		url: "https://mamaschoice.in/",
		image: "/projects/mamaschoice.jpg",
		description: "Mamas choice is a catalog website for an infant clothing brand. It is built using Next.js.",
		languages: ["TypeScript", "Next.js"],
		
	},
	{
		title: "Focus Technolab",
		url: "https://www.focustechnolab.com/",
		image: "/projects/focustechnolab.png",
		description: "Focus Technolab is a website for a software development company. It is built using Next.js.",
		languages: ["TypeScript", "Next.js"],
	},
	{
		title: "BDICC",
		url: "https://www.bluediamondicc.com/",
		image: "/projects/bdicc.png",
		description: "Blue Diamond ICC is a website for my convention center located in Kerala, India. It is built using Next.js.",
		languages: ["JavaScript", "Next.js"],
	},
	{
		title: "Tekloom",
		url: "https://tekloom.com/",
		image: "/projects/tekloom.png",
		description: "Tekloom is a website for a software development company. It is built using Next.js.",
		languages: ["JavaScript", "Next.js"],
	},
	{
		title: "Ignite AI",
		url: "https://discover.igniteme.in/",
		image: "/projects/ignite.png",
		description: "Ignite AI is an AI based chat bot that assesses the strengths and weaknesses of students and provides them with a personalized career path. It is built using React.js and MongoDb.",
		languages: ["JavaScript", "React", "MongoDb", "AI", "Express.js"],
	},
	{
		title: "Seed Innovations",
		url: "https://www.seedinnovations.in/",
		image: "/projects/seedinnvoations.png",
		description: "Seed Innovations is a website for a technology company. It is built using Next.js.",
		languages: ["JavaScript", "Next.js", "MongoDb"],
	},
	{
		title: "E-Janamaithri",
		url: "https://github.com/hamsathul/e-janamaithri",
		image: "/projects/ejanamaithri.png",
		description: "E-Janamaithri is a web application that helps the police department to manage the complaints and cases. It is built using Django.",
		languages: ["Python", "Django", "Sqlite"],
	},
	{
		title: "BD Tailoring",
		url: "https://www.bluediamond.ae/",
		image: "/projects/bluediamondae.png",
		description: "Blue Diamond Tailoring is a website for my abaya manufacturing company. It is built using Next.js.",
		languages: ["JavaScript", "Next.js"],
	},
	{
		title: "Moi App (Hackathon Project)",
		url: "https://moi-app.vercel.app/",
		image: "/projects/moi.png",
		description: "Moi App is our teams implementation of our hackathon project. it is built using Next.js, three.js.",
		languages: ["JavaScript", "Next.js", "Three.js"],
	},
	{
		title: "ERP System with POS",
		url: "https://github.com/hamsathul/pos_laravel",
		image: "/projects/poslaravel.webp",
		description: "A full ERP systerm with Point of sale funtionality made with Laravel.",
		languages: ["Php", "Laravel", "Mysql"],
	},
	{
		title: "Nextjs Dashboard",
		url: "https://nextjs-dashboard-lime-alpha-54.vercel.app/dashboard",
		image: "/projects/nextdashboard.png",
		description: "A simple dashboard built using Next.js and postgres.",
		languages: ["TypeScript", "Next.js", "Postgres"],
	},
	{
		title: "Robolab",
		url: "https://github.com/hamsathul/robolab-website",
		image: "/projects/robolab.webp",
		description: "An expirmental 3d website underdevelopment to test out the different features of 3d web devlopment using React Three Fiber.",
		languages: ["TypeScript", "Next.js", "Three.js"],
	},
	{
		title: "Blog App",
		url: "https://github.com/hamsathul/blogapp_django",
		image: "/projects/djangoblog.webp",
		description: "A simple blog app built using Django.",
		languages: ["Python", "Django", "Sqlite"],
	},
	{
		title: "Proshop Ecommerce",
		url: "https://github.com/hamsathul/proshop",
		image: "/projects/proshop.webp",
		description: "An electronics shop ecommerce site using MERN stack.",
		languages: ["JavaScript", "Express.js", "MongoDb", "React"],
	},
	{
		title: "DocsChat - AI",
		url: "https://github.com/hamsathul/docs_chat",
		image: "/projects/docschat.png",
		description: "An OpenAI based webapp to chat with a given document for regarding its content using RAG.",
		languages: ["Python", "Streamlit",  "AI"],
	},
	{
		title: "Skillbridge - AI",
		url: "https://github.com/hamsathul/skillbridge",
		image: "/projects/skillbridge.png",
		description: "An OpenAI based webapp wherin user is asked questions based on a random questionnare to find the percentage of Enterpreunership vs Employee mentality.",
		languages: ["Python", "Streamlit",  "AI"],
	},
	{
		title: "Transcendance",
		url: "https://github.com/Aztaro97/transandence-project",
		image: "/projects/transcendance.webp",
		description: "Transcendance is 42 school's final project for the common core. it is a pong and tic-tac-toe game built using Django.",
		languages: ["JavaScript", "Python", "Django", "Postgres", "42Project", "Docker", "Grafana", "Prometheus", ],
	},
	{
		title: "ft_irc",
		url: "https://github.com/Aztaro97/ft_irc",
		image: "/projects/irc.webp",
		description: "ft_irc is a simple IRC server built using C++. It is a project from 42 school curriculum. We should be able to use any client to connect to the server.",
		languages: ["C++", "42Project"],
	},
	{
		title: "Inception",
		url: "https://github.com/hamsathul/inception",
		image: "/projects/inception.jpeg",
		description: "Inception is a 42 school project that deals with containers and virtualization.",
		languages: ["Docker", "42Project"],
	},
	{
		title: "Cub3D",
		url: "https://github.com/samiyazbr/Cub3D",
		image: "/projects/cub3d.png",
		description: "cub3d is a 3D maze game built using C and Raycasting algorithm. It is a project from 42 school curriculum.",
		languages: ["C", "42Project"],
	},
	{
		title: "CPP Piscine",
		url: "https://github.com/hamsathul/cpp_modules",
		image: "/projects/42logo.jpg",
		description: "Cpp piscine is a set of 42 projects that aims to be an introduction to C++.",
		languages: ["C++", "42Project"],
	},
	{
		title: "Mini Shell",
		url: "https://github.com/hamsathul/minishell",
		image: "/projects/minishell.png",
		description: "Minishell is a 42 project to create a shell what works similar to bash using c.",
		languages: ["C", "42Project"],
	},
	{
		title: "Philosophers",
		url: "https://github.com/hamsathul/philosophers",
		image: "/projects/philo.png",
		description: "Philosophers is a 42 project that aims to teach concurrent programming, focusing on multithreading and multiprocessing.",
		languages: ["C", "42Project"],
	},
	{
		title: "Pipex",
		url: "https://github.com/hamsathul/pipex",
		image: "/projects/pipex.png",
		description: "pipex is a 42 project that aims to teach about redirection and pipes.",
		languages: ["C", "42Project"],
	},
	{
		title: "FDF",
		url: "https://github.com/hamsathul/fdfmac_os",
		image: "/projects/fdf.png",
		description: "FDF is a 42 project about creating a simple wireframe model representation of a 3D landscape by linking various points (x, y, z) thanks to line segments (edges).",
		languages: ["C", "42Project"],
	},
	{
		title: "Push Swap",
		url: "https://github.com/hamsathul/push_swap",
		image: "/projects/pushswap.png",
		description: "Push swap is a 42 project that teaches about sorting algorithms and aims at  sorting data on a stack, with a limited set of instructions, and the smallest number of moves.",
		languages: ["C", "42Project"],
	},
	{
		title: "Get Next Line",
		url: "https://github.com/hamsathul/get_next_line",
		image: "/projects/42logo.jpg",
		description: "Get next line is a 42 project that aims to teach about reading a file line by line.",
		languages: ["C", "42Project"],
	},
	{
		title: "Ft_printf",
		url: "https://github.com/hamsathul/ft_printf",
		image: "/projects/42logo.jpg",
		description: "Ft_printf is a 42 project that aims at recoding the system function printf. This project is a great way to learn about variadic functions.",
		languages: ["C", "42Project"],
	},
	{
		title: "Libft",
		url: "https://github.com/hamsathul/libft",
		image: "/projects/42logo.jpg",
		description: "Libft is a 42 project that aims to create a library of useful functions.",
		languages: ["C", "42Project"],
	},

];